export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SEARCH_SONG = 'SEARCH_SONG'
export const SEARCH__ASYNC_SONG = 'SEARCH_ASYNC_SONG'
export const IS_LOADING = 'IS_LOADING'
